# Generated by Django 5.2.6 on 2025-09-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.PositiveIntegerField()),
                ('calorias', models.PositiveIntegerField()),
                ('inventario', models.PositiveIntegerField()),
                ('es_vegetariano', models.BooleanField()),
                ('es_sano', models.BooleanField()),
                ('tipo', models.CharField(choices=[('Base', 'Base'), ('Complemento', 'Complemento')], max_length=16)),
                ('sabor', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
