# Generated by Django 5.2.6 on 2025-09-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_publico', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Copa', 'Copa'), ('Malteada', 'Malteada')], max_length=8)),
                ('vaso', models.CharField(max_length=200, null=True)),
                ('volumen_onzas', models.PositiveIntegerField(null=True)),
                ('ingredientes', models.ManyToManyField(to='ventas.ingrediente')),
            ],
        ),
    ]
