# Generated by Django 4.2.24 on 2025-09-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('anio_publicacion', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libros.autor')),
            ],
        ),
    ]
