# Generated by Django 4.2.24 on 2025-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='anio_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
