# Generated by Django 4.2.24 on 2025-09-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_portada',
            field=models.FileField(default='pruebas.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
