# Generated by Django 4.2.24 on 2025-09-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
    ]
